name: Set Gateway URL on environment variables
description: Set environment gateway url on variables for the workflow
title: "[Set Gateway URL] Configure gateway URL in environment variables"
labels: ["automation"]
body:
  - type: input
    id: env_url
    attributes:
      label: "Enter the Gateway URL"
      description: "Provide the Gateway URL to be used for environment variables."
      placeholder: "https://example.com"
    validations:
      required: true